=== foomoon/PillarOfLight/data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "definitions": {
        "rgb": {
            "type": "integer",
            "minimum": 0,
            "maximum": 255
          },
        "colorStop": {
              "type": "object",
              "properties": {
                "pos": {"$ref": "definitions/rgb"},
                "r": {"$ref": "definitions/rgb"},
                "g": {"$ref": "definitions/rgb"},
                "b": {"$ref": "definitions/rgb"}
              },
              "required": [
                "pos",
                "r",
                "g",
                "b"
              ]
            },
        "gradient": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["gradient"]
              },
              "value": {
                "type": "array",
                "items":  {"$ref": "definitions/colorStop"}
              },
              "mapto": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "value",
              "mapto"
            ]
          },
        "range": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "class": {
                "type": "string"
              },
              "min": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              },
              "max": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              },
              "step": {
                "type": "integer",
                "minimum": 1,
                "maximum": 255
              },
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "mapto": {
                "type": "string"
              },
              "reverse": {
                "type": "boolean"
              },
              "value": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              }
            },
            "required": [
              "type",
              "class",
              "value",
              "min",
              "max",
              "step"
            ]
          },
          "color": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "class": {
                "type": "string"
              },
              "value": {
                "type": "array",
                "items": [
                    {"$ref": "definitions/rgb"},
                    {"$ref": "definitions/rgb"},
                    {"$ref": "definitions/rgb"}
                ]
              }
            },
            "required": [
              "type",
              "class",
              "value"
            ]
          }
    },
    "properties": {
      "timestamp": {
        "type": "string",
        "format":"date-time",
        "pattern": "^(.*)$",
        "examples": ["2019-05-03T06:25:51.238000Z"]
      },
      "size": {
        "type": "integer",
        "minimum": 10,
        "maximum": 85
      },
      "selected": {
        "type": "string",
        "enum": ["fire","scanner"]
      },
      "effects": {
        "type": "object",
        "properties": {
          "fire": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "object",
                "properties": {
                  "gradient": {"$ref": "definitions/gradient"},
                  "brightness": {"$ref": "definitions/range"},
                  "speed": {"$ref": "definitions/range"},
                  "intensity": {"$ref": "definitions/range"},
                  "size": {"$ref": "definitions/range"}
                },
                "required": [
                  "gradient",
                  "brightness",
                  "speed",
                  "intensity",
                  "size"
                ]
              }
            },
            "required": [
              "name",
              "data"
            ]
          },
          "scanner": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "data": {
                "type": "object",
                "properties": {
                  "color": {"$ref": "definitions/color"},
                  "speed": {"$ref": "definitions/range"},
                  "spread": {"$ref": "definitions/range"}
                },
                "required": [
                  "color",
                  "speed",
                  "spread"
                ]
              }
            },
            "required": [
              "name",
              "data"
            ]
          }
        },
        "required": [
          "fire",
          "scanner"
        ]
      }
    },
    "required": [
      "timestamp",
      "size",
      "selected",
      "effects"
    ]
  }

=== foomoon/PillarOfLight/data/saved_effects.json
{
    "timestamp": "2020-09-07T20:29:19.882Z",
    "size": 50,
    "selected": "fire",
    "effects": {
        "fire": {
            "name": "fire",
            "data": {
                "gradient": {
                    "type": "gradient",
                    "value": [
                        {
                            "pos": 0,
                            "r": 0,
                            "g": 0,
                            "b": 0
                        },
                        {
                            "pos": 84,
                            "r": 0,
                            "g": 0,
                            "b": 255
                        },
                        {
                            "pos": 173,
                            "r": 0,
                            "g": 255,
                            "b": 255
                        },
                        {
                            "pos": 255,
                            "r": 255,
                            "g": 255,
                            "b": 255
                        }
                    ],
                    "mapto": "PALETTE"
                },
                "brightness": {
                    "type": "range",
                    "class": "enabled",
                    "min": 0,
                    "max": 255,
                    "step": 1,
                    "id": "brightness-slider",
                    "name": "brightness",
                    "value": 65
                },
                "speed": {
                    "type": "range",
                    "class": "enabled",
                    "min": 10,
                    "max": 60,
                    "step": 1,
                    "mapto": "FRAMES_PER_SECOND",
                    "id": "speed-slider",
                    "name": "speed",
                    "value": 60
                },
                "intensity": {
                    "type": "range",
                    "class": "enabled",
                    "min": 50,
                    "max": 200,
                    "step": 1,
                    "mapto": "SPARKING",
                    "id": "intensity-slider",
                    "name": "intensity",
                    "value": 80
                },
                "size": {
                    "type": "range",
                    "class": "enabled",
                    "min": 20,
                    "max": 100,
                    "step": 1,
                    "mapto": "COOLING",
                    "reverse": true,
                    "id": "size-slider",
                    "name": "size",
                    "value": 50
                }
            }
        },
        "scanner": {
            "name": "scanner",
            "data": {
                "color": {
                    "type": "color",
                    "class": "colorpick",
                    "value": [
                        0,
                        0,
                        255
                    ]
                },
                "speed": {
                    "type": "range",
                    "class": "enabled",
                    "value": 2,
                    "min": 1,
                    "max": 10,
                    "step": 1,
                    "reverse": true
                },
                "spread": {
                    "type": "range",
                    "class": "enabled",
                    "value": 12,
                    "min": 1,
                    "max": 20,
                    "step": 1
                }
            }
        }
    }
}
